fix pull to handle if data tables is not enabled in secops

diff --git a/.github/workflows/Pull Latest Content.yml b/.github/workflows/Pull Latest Content.yml
--- a/.github/workflows/Pull Latest Content.yml
+++ b/.github/workflows/Pull Latest Content.yml
@@ -67,7 +67,7 @@ jobs:
         run: python -m content_manager rules get
 
       - name: Pull latest version of all data tables from Google SecOps
-        run: python -m content_manager data-tables get
+        run: python -m content_manager data-tables get || (grep -q 'Precondition check failed' error.log && echo 'Skipping step due to precondition failure')
 
       - name: Pull latest version of all reference lists from Google SecOps
         run: python -m content_manager reference-lists get
